version: '3.1'

services:

  nginx:
    restart: always
    image: zhicongdai/lnmp_nginx
    container_name: "nginx_container"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./letsencrypt:/etc/letsencrypt
    - ./www/html/:/var/www/html/
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./nginx.d/:/etc/nginx/conf.d/
    depends_on:
    - "phpfpm7"
    networks:
      hx_net:
        ipv4_address: 172.20.199.2

  phpfpm7:
    restart: always
    image: zhicongdai/qnphp
    container_name: "phpfpm7_conrainer"
    depends_on:
    - "mysql"
    - "redis"
    volumes:
    - ./php.ini:/usr/local/etc/php/php.ini
    - ./www/html/:/var/www/html/
    - ./data/:/data/
    - ./php-fpm.d/:/usr/local/etc/php-fpm.d/
    networks:
      hx_net:
        ipv4_address: 172.20.199.3

  mysql:
    image: zhicongdai/lnmp_mysql
    container_name: "mysql_container"
    privileged: true
    ports:
    - "3306:3306"
    volumes:
    - ./sqldata/data/:/var/lib/mysql/
    - ./sqldata/:/var/local/

    environment:
      MYSQL_ROOT_PASSWORD: zhicongdai
    networks:
      hx_net:
        ipv4_address: 172.20.199.4

  redis:
    image: zhicongdai/lnmp_redis
    container_name: "redis_container"
    ports:
    - "6379:6379"
    networks:
      hx_net:
        ipv4_address: 172.20.199.5

  elasticsearch:
    restart: always
    container_name: "elasticsearch_container"
    image: zhicongdai/elasticsearch
    ports:
    - "9200:9200"
    networks:
      hx_net:
        ipv4_address: 172.20.199.6

networks:
  hx_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.199.1/24
